In [1]:
import pandas as pd
import numpy as np

In [2]:
employees = pd.read_csv('employee_data.csv')
orders = pd.read_csv('ecom_orders.csv')


In [3]:
employees

EmployeeID     Name Department  Age  Experience  Salary  Bonus  \
0         101    Alice         IT   29           5   75000   5000   
1         102      Bob    Finance   35          10   88000   7000   
2         103  Charlie         HR   28           4   65000   4000   
3         104    David         IT   42          15  120000  10000   
4         105      Eva  Marketing   31           7   78000   6000   
5         106    Frank    Finance   45          20  135000  12000   
6         107    Grace         HR   26           3   60000   3500   
7         108    Helen  Marketing   39          12   98000   8000   
8         109      Ian         IT   33           8   85000   6500   
9         110     Jane    Finance   30           6   79000   5500   

   PerformanceScore              Email  
0                88    alice@gmail.com  
1                92      bob@yahoo.com  
2                85  charlie@gmail.com  
3                95  david@outlook.com  
4                90      eva@gmail.com  
5                97    frank@yahoo.com  
6                80  grace@company.com  
7                93  helen@outlook.com  
8                89      ian@gmail.com  
9                87     jane@yahoo.com

In [4]:
orders

OrderID CustomerID   OrderDate Country     Category  Quantity  UnitPrice  \
0     2001       C001  2025-07-01     USA  Electronics         1     799.99   
1     2002       C002  2025-07-02  Canada      Fashion         3      49.99   
2     2003       C003  2025-07-02     USA         Home         2     129.50   
3     2004       C004  2025-07-03      UK  Electronics         1     999.00   
4     2005       C001  2025-07-03     USA        Books         5      15.00   
5     2006       C005  2025-07-04   India      Fashion         2      39.99   
6     2007       C006  2025-07-04     USA         Home         1     249.99   
7     2008       C007  2025-07-05      UK  Electronics         2     499.50   
8     2009       C008  2025-07-05     USA      Fashion         4      29.99   
9     2010       C009  2025-07-06  Canada        Books         7      12.99   

   Discount              Email  
0      0.10    alice@gmail.com  
1      0.00      bob@yahoo.com  
2      0.05  charlie@gmail.com  
3      0.15   dave@outlook.com  
4      0.00      eva@gmail.com  
5      0.20    frank@yahoo.com  
6      0.00  grace@company.com  
7      0.05  helen@outlook.com  
8      0.10      ian@gmail.com  
9      0.00     jane@yahoo.com

In [5]:
#IT employee over 30

In [12]:
itemp30 = employees[(employees['Age']>30) & (employees['Department'] == 'IT')]

In [13]:
itemp30

EmployeeID   Name Department  Age  Experience  Salary  Bonus  \
3         104  David         IT   42          15  120000  10000   
8         109    Ian         IT   33           8   85000   6500   

   PerformanceScore              Email  
3                95  david@outlook.com  
8                89      ian@gmail.com

In [18]:
it_over_30_q = employees.query('Department == "IT" and Age > 30 and Name.str.contains("David")')
it_over_30_q

EmployeeID   Name Department  Age  Experience  Salary  Bonus  \
3         104  David         IT   42          15  120000  10000   

   PerformanceScore              Email  
3                95  david@outlook.com

In [19]:
#frequency of each dept

In [20]:
depts = employees['Department'].value_counts()

In [21]:
depts

Department
IT           3
Finance      3
HR           2
Marketing    2
Name: count, dtype: int64

In [22]:
deptscount = employees['Department'].count()
deptscount

np.int64(10)

In [40]:
avgsalary1= employees.groupby(['Department'])['Salary'].mean()
avgsalary1

Department
Finance      100666.666667
HR            62500.000000
IT            93333.333333
Marketing     88000.000000
Name: Salary, dtype: float64

In [25]:
avgbonus= employees.groupby(['Department'])['Bonus'].mean()
avgbonus

Department
Finance      8166.666667
HR           3750.000000
IT           7166.666667
Marketing    7000.000000
Name: Bonus, dtype: float64

In [28]:
dept_agg = employees.groupby(['Department']).agg(
         avgsalary=('Salary','mean'),
    avgbonus=('Bonus','mean'),
    headcount=('EmployeeID','count')
).sort_values('avgsalary',ascending=False)
dept_agg

avgsalary     avgbonus  headcount
Department                                       
Finance     100666.666667  8166.666667          3
IT           93333.333333  7166.666667          3
Marketing    88000.000000  7000.000000          2
HR           62500.000000  3750.000000          2

In [44]:
high_debt = employees.groupby('Department').filter(lambda x:x['Salary'].mean()>90000).sort_values('Salary',ascending=False)

In [45]:
high_debt.head()

EmployeeID   Name Department  Age  Experience  Salary  Bonus  \
5         106  Frank    Finance   45          20  135000  12000   
3         104  David         IT   42          15  120000  10000   
1         102    Bob    Finance   35          10   88000   7000   
8         109    Ian         IT   33           8   85000   6500   
9         110   Jane    Finance   30           6   79000   5500   

   PerformanceScore              Email  
5                97    frank@yahoo.com  
3                95  david@outlook.com  
1                92      bob@yahoo.com  
8                89      ian@gmail.com  
9                87     jane@yahoo.com

In [48]:
splitemail = employees['Email'].apply(lambda x: x.split('@')[0])
splitemail

0      alice
1        bob
2    charlie
3      david
4        eva
5      frank
6      grace
7      helen
8        ian
9       jane
Name: Email, dtype: object

In [49]:
orders['LineTotal'] = orders['Quantity'] * orders['UnitPrice'] * (1 - orders['Discount'])
orders[['OrderID','Quantity','UnitPrice','Discount','LineTotal']].head()

OrderID  Quantity  UnitPrice  Discount  LineTotal
0     2001         1     799.99      0.10    719.991
1     2002         3      49.99      0.00    149.970
2     2003         2     129.50      0.05    246.050
3     2004         1     999.00      0.15    849.150
4     2005         5      15.00      0.00     75.000

In [53]:
rev= orders.groupby(['Country','Category'])['LineTotal'].sum().reset_index()

In [55]:
rev.head()

Country     Category  LineTotal
0  Canada        Books     90.930
1  Canada      Fashion    149.970
2   India      Fashion     63.984
3      UK  Electronics   1798.200
4     USA        Books     75.000

In [56]:
arr = employees[['Age','Experience','Salary','Bonus','PerformanceScore']].to_numpy()
arr[:5], arr.shape, arr.dtype

(array([[    29,      5,  75000,   5000,     88],
        [    35,     10,  88000,   7000,     92],
        [    28,      4,  65000,   4000,     85],
        [    42,     15, 120000,  10000,     95],
        [    31,      7,  78000,   6000,     90]]),
 (10, 5),
 dtype('int64'))

In [60]:
np_mean= np.std(arr,axis=1)
np_mean

array([29550.30163366, 34591.32849487, 25634.25866765, 47142.55485907,
       30674.10971226, 52986.18873858, 23677.14555769, 38508.96146821,
       33430.66763916, 31109.63863242])

In [61]:
min_vals = arr.min(axis=0)
max_vals = arr.max(axis=0)
scaled = (arr - min_vals) / (max_vals - min_vals)
scaled[:5]

array([[0.15789474, 0.11764706, 0.2       , 0.17647059, 0.47058824],
       [0.47368421, 0.41176471, 0.37333333, 0.41176471, 0.70588235],
       [0.10526316, 0.05882353, 0.06666667, 0.05882353, 0.29411765],
       [0.84210526, 0.70588235, 0.8       , 0.76470588, 0.88235294],
       [0.26315789, 0.23529412, 0.24      , 0.29411765, 0.58823529]])

In [70]:
top3= employees.groupby(['Department']).head(2).sort_values('Department').reset_index()
top3

index  EmployeeID     Name Department  Age  Experience  Salary  Bonus  \
0      1         102      Bob    Finance   35          10   88000   7000   
1      5         106    Frank    Finance   45          20  135000  12000   
2      2         103  Charlie         HR   28           4   65000   4000   
3      6         107    Grace         HR   26           3   60000   3500   
4      0         101    Alice         IT   29           5   75000   5000   
5      3         104    David         IT   42          15  120000  10000   
6      4         105      Eva  Marketing   31           7   78000   6000   
7      7         108    Helen  Marketing   39          12   98000   8000   

   PerformanceScore              Email  
0                92      bob@yahoo.com  
1                97    frank@yahoo.com  
2                85  charlie@gmail.com  
3                80  grace@company.com  
4                88    alice@gmail.com  
5                95  david@outlook.com  
6                90      eva@gmail.com  
7                93  helen@outlook.com

In [78]:
meanemp30 = employees[(employees['Age']>30)].groupby(['Department'])['PerformanceScore'].mean()
meanemp30

Department
Finance      94.5
IT           92.0
Marketing    91.5
Name: PerformanceScore, dtype: float64

In [82]:
orders["OrderDate"] = pd.to_datetime(orders["OrderDate"])

In [83]:
orders["Revenue"] = orders["Quantity"] * orders["UnitPrice"] * (1 - orders["Discount"])

In [84]:
orders["Month"] = orders["OrderDate"].dt.to_period("M")

In [85]:
monthly_revenue = orders.groupby("Month")["Revenue"].sum()
monthly_revenue

Month
2025-07    3502.079
Freq: M, Name: Revenue, dtype: float64

In [86]:
employees["TotalCompensation"] = employees["Salary"]+employees["Bonus"]

In [101]:
deptavg= (employees.groupby(["Department"])["TotalCompensation"].mean().sort_values(ascending=False))
deptavg                                         

Department
Finance      108833.333333
IT           100500.000000
Marketing     95000.000000
HR            66250.000000
Name: TotalCompensation, dtype: float64

In [109]:
emailtld = employees["Email"].apply(lambda x: x.split('.')[1])
emailtld.value_counts()

Email
com    10
Name: count, dtype: int64

In [110]:
employees["Salary"].to_numpy

<bound method IndexOpsMixin.to_numpy of 0     75000
1     88000
2     65000
3    120000
4     78000
5    135000
6     60000
7     98000
8     85000
9     79000
Name: Salary, dtype: int64>

In [114]:
mean= employees["Salary"].mean()
sd= employees["Salary"].std()
mean
sd

23579.88785196213

In [115]:
mean
sd

23579.88785196213

In [121]:
employees["zsalary"]=(employees["Salary"] - mean)/sd

In [124]:
employees[["Name", "Salary", "zsalary"]]

def check(a):
    if(a == 0):
        return "Normal Salary"
    if(a < 0):
        return "Below average"
    else:
        return "Above average"
employees["meaning"] = check(employees["zsalary"])
employees[["Name", "Salary", "zsalary","meaning"]]



ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().